
name: Node.JS CI
on: [push, pull_request]
jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-16.04 
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn ci
